### ISSUE TITLE
Not instantiable – yii\di\NotInstantiableException

### ISSUE THREAD

**Issue by mysoundmagic** [akiraz2/yii2-blog#19]
**Describe the bug**
I have followed the installation instruction
but always get error not instantiable
error message:
```
ReflectionException: Class yii\bootstrap\BootstrapAsset does not exist in /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php:507
Stack trace:
#0 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php(507): ReflectionClass->__construct()
#1 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#2 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#3 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#4 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject()
#5 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle()
#6 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#7 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#8 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetBundle()
#9 /home/ubuntu/Documents/workspace/blogapp/vendor/akiraz2/yii2-blog/views/frontend/default/index.php(11): yii\web\AssetBundle::register()
#10 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(347): require('/home/ubuntu/...')
#11 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#12 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#13 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#14 /home/ubuntu/Documents/workspace/blogapp/vendor/akiraz2/yii2-blog/controllers/frontend/DefaultController.php(61): yii\base\Controller->render()
#15 [internal function]: akiraz2\blog\controllers\frontend\DefaultController->actionIndex()
#16 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#17 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#18 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#19 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#20 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#21 /home/ubuntu/Documents/workspace/blogapp/frontend/web/index.php(18): yii\base\Application->run()
#22 {main}

Next yii\di\NotInstantiableException: Failed to instantiate component or class "yii\bootstrap\BootstrapAsset". in /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php:509
Stack trace:
#0 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php(385): yii\di\Container->getDependencies()
#1 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build()
#2 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get()
#3 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetManager.php(286): yii\BaseYii::createObject()
#4 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetManager.php(259): yii\web\AssetManager->loadBundle()
#5 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/View.php(294): yii\web\AssetManager->getBundle()
#6 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/View.php(299): yii\web\View->registerAssetBundle()
#7 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/AssetBundle.php(125): yii\web\View->registerAssetBundle()
#8 /home/ubuntu/Documents/workspace/blogapp/vendor/akiraz2/yii2-blog/views/frontend/default/index.php(11): yii\web\AssetBundle::register()
#9 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(347): require('/home/ubuntu/...')
#10 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile()
#11 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#12 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Controller.php(407): yii\base\View->render()
#13 /home/ubuntu/Documents/workspace/blogapp/vendor/akiraz2/yii2-blog/controllers/frontend/DefaultController.php(61): yii\base\Controller->render()
#14 [internal function]: akiraz2\blog\controllers\frontend\DefaultController->actionIndex()
#15 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#16 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#17 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#18 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#19 /home/ubuntu/Documents/workspace/blogapp/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#20 /home/ubuntu/Documents/workspace/blogapp/frontend/web/index.php(18): yii\base\Application->run()
#21 {main}
```

here is my common/config/main.php
```
<?php
return [
    'aliases' => [
        '@bower' => '@vendor/bower-asset',
        '@npm'   => '@vendor/npm-asset',
    ],
    'vendorPath' => dirname(dirname(__DIR__)) . '/vendor',
    'bootstrap' => [\akiraz2\blog\Bootstrap::class],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
    ],
    'modules' => [
        'blog' => [
            'class' => akiraz2\blog\Module::class,
            'urlManager' => 'urlManager',// 'urlManager' by default, or maybe you can use own component urlManagerFrontend
            'imgFilePath' => '@frontend/web/img/blog/',
            'imgFileUrl' => '/img/blog/',
            'userModel' => \common\models\User::class,
            'userPK' => 'id', //default primary key for {{%user}} table
            'userName' => 'username', //uses in view (may be field `username` or `email` or `login`)
        ],
     ],
];
```

here is my frontend/config/main.php
```
<?php
$params = array_merge(
    require __DIR__ . '/../../common/config/params.php',
    require __DIR__ . '/../../common/config/params-local.php',
    require __DIR__ . '/params.php',
    require __DIR__ . '/params-local.php'
);

return [
    'id' => 'app-frontend',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log'],
    'controllerNamespace' => 'frontend\controllers',
    'modules'=>[
        'blog' => [
            'class' => 'akiraz2\blog\Module',
            'controllerNamespace' => 'akiraz2\blog\controllers\frontend',
            'blogPostPageCount' => 6,
            'blogCommentPageCount' => 10, //20 by default
            'enableComments' => true, //false by default
            'schemaOrg' => [ // empty array [] by default! 
                'publisher' => [
                    'logo' => '/img/logo.png',
                    'logoWidth' => 191,
                    'logoHeight' => 74,
                    'name' => 'My Company',
                    'phone' => '+1 800 488 80 85',
                    'address' => 'City, street, house'
                ]
            ]
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-frontend',
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-frontend', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the frontend
            'name' => 'advanced-frontend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        'formatter' => [ //for the showing of date datetime
            'dateFormat' => 'dd-MM-yyyy',
            'datetimeFormat' => 'dd-MM-yyyy HH:mm:ss',
            'decimalSeparator' => ',',
            'thousandSeparator' => '.',
            'currencyCode' => 'USD ',
        ],
        
    ],
    'params' => $params,
];
```

here is my backend/config/main.php
```
<?php
$params = array_merge(
    require __DIR__ . '/../../common/config/params.php',
    require __DIR__ . '/../../common/config/params-local.php',
    require __DIR__ . '/params.php',
    require __DIR__ . '/params-local.php'
);

return [
    'id' => 'app-backend',
    'basePath' => dirname(__DIR__),
    'controllerNamespace' => 'backend\controllers',
    'bootstrap' => ['log'],
    'modules' => [
        'blog' => [
            'class' => 'akiraz2\blog\Module',
            'controllerNamespace' => 'akiraz2\blog\controllers\backend',
            //'adminAccessControl' => 'common\components\AdminAccessControl', // null - by default 
        ],
    ],
    'components' => [
        'request' => [
            'csrfParam' => '_csrf-backend',
        ],
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'identityCookie' => ['name' => '_identity-backend', 'httpOnly' => true],
        ],
        'session' => [
            // this is the name of the session cookie used for login on the backend
            'name' => 'advanced-backend',
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'showScriptName' => false,
            'rules' => [
            ],
        ],
        'formatter' => [ //for the showing of date datetime
            'dateFormat' => 'dd-MM-yyyy',
            'datetimeFormat' => 'dd-MM-yyyy HH:mm:ss',
            'decimalSeparator' => ',',
            'thousandSeparator' => '.',
            'currencyCode' => 'USD ',
        ],
    ],
    'params' => $params,
];

```
 - OS: ubuntu 20.04
 - Browser chrome
 - Version 101.xx
- PHP 7.4.3

**Comment by mysoundmagic** [comment]
change 
`'yii\bootstrap\BootstrapAsset',`
to
`'yii\bootstrap4\BootstrapAsset'`

vendor/akiraz2/assets/AppAsset.php
